### ISSUE TITLE
Result Hreflang Checker Bug

### ISSUE THREAD

**Issue by geofany** [cmlabsdev/tools#308]
Result on Hreflang Checker is Wrong

Before Crawl 
![image](https://user-images.githubusercontent.com/37582643/108469131-5033fd00-72ba-11eb-81bc-3e059fcbec6a.png)

After Crawl 
![image](https://user-images.githubusercontent.com/37582643/108469160-5b872880-72ba-11eb-804a-eacfb5e0604e.png)

it must be like this
Before Crawl 
![image](https://user-images.githubusercontent.com/37582643/108469186-65a92700-72ba-11eb-9167-98fda06937b3.png)

After Crawl
![image](https://user-images.githubusercontent.com/37582643/108469207-6c379e80-72ba-11eb-96d9-1bafda2c621d.png)

**Comment by geofany** [comment]
![image](https://user-images.githubusercontent.com/37582643/109438769-e1933400-7a5d-11eb-8047-4a602427ddb5.png)
still not right on before crawl

**Comment by miqdadyyy** [comment]
https://github.com/cmlabsdev/tools/pull/335
