### ISSUE TITLE
Convert to Lower Case

### ISSUE THREAD

**Issue by geofany** [cmlabsdev/tools#327]
![image](https://user-images.githubusercontent.com/37582643/109116503-40616080-7773-11eb-9df2-4d44fd727e34.png)
Convert URL Text to Lower Case

**Comment by geofany** [comment]
![image](https://user-images.githubusercontent.com/37582643/109438949-db518780-7a5e-11eb-990f-a4948e202dc8.png)
still Uppercase after crawl

and cannot crawl URL with http or https

@WisnuDS

**Comment by WisnuDS** [comment]
subject to cors policy when trying to fix the bug, can I ask for help checking for the API server side? @miqdadyyy @ermanuk
