### ISSUE TITLE
Need Copy

### ISSUE THREAD

**Issue by geofany** [cmlabsdev/tools#371]
### All Tools need this Copy Section
A (800 Char) 
- [ ] Word Counter
- [ ] Meta Checker
- [ ] JSON LD Home
- [ ] JSON LD Breadcrumb
- [ ] JSON LD FAQ Page
- [ ] JSON LD How To
- [ ] JSON LD Job Posting
- [ ] JSON LD Person
- [ ] JSON LD Product
- [ ] JSON LD Recipe
- [ ] Page Speed Test
- [ ] Sitemap Generator
- [ ] Mobile Friendly Test
- [ ] SSL Checker
- [ ] Robot TXT Generator
- [ ] Redirect Chain Checker
- [ ] Technology Lookup
- [ ] Link Analyzer
- [ ] Hreflang Checker

B (120 Char)
- [ ] Word Counter
- [ ] Meta Checker
- [ ] JSON LD Home
- [ ] JSON LD Breadcrumb
- [ ] JSON LD FAQ Page
- [ ] JSON LD How To
- [ ] JSON LD Job Posting
- [ ] JSON LD Person
- [ ] JSON LD Product
- [ ] JSON LD Recipe
- [ ] Page Speed Test
- [ ] Sitemap Generator
- [ ] Mobile Friendly Test
- [ ] SSL Checker
- [ ] Robot TXT Generator
- [ ] Redirect Chain Checker
- [ ] Technology Lookup
- [ ] Link Analyzer
- [ ] Hreflang Checker

![image](https://user-images.githubusercontent.com/37582643/110423772-442aa680-80d4-11eb-97f9-2bec2f9935e0.png)

### Missing Copy on HomePage
Home Desc (200 Char)
- [x] JSON LD Home
- [x] Robots TXT Generator

![image](https://user-images.githubusercontent.com/37582643/110424234-0da15b80-80d5-11eb-96d9-e5a6a7eccc75.png)

### Missing Meta Title, Meta Desc and Subtitle
- [x] JSON LD Home
- [x] Robots TXT Generator

### Missing Description
- [x] Recipe JSON LD

**Comment by miqdadyyy** [comment]
Okay
