### ISSUE TITLE
Bug on FAQ JSON LD

### ISSUE THREAD

**Issue by geofany** [cmlabsdev/tools#395]
### Bug Number 1
when my data like this
![image](https://user-images.githubusercontent.com/37582643/110947869-452d3380-8373-11eb-925e-87e35f5e199c.png)

then delete number 2 Data.
the Data on number 1 is gone
![image](https://user-images.githubusercontent.com/37582643/110947955-5d04b780-8373-11eb-91d0-910690bf4259.png)

### Bug Number 2
when i add more than 2 new Data
![image](https://user-images.githubusercontent.com/37582643/110948046-773e9580-8373-11eb-80f8-189edb5e4f44.png)

i can't delete the lastest one
![image](https://user-images.githubusercontent.com/37582643/110948108-845b8480-8373-11eb-941f-1e3c50fa931a.png)

### Bug Number 3
when my data like this
![image](https://user-images.githubusercontent.com/37582643/110948325-ca184d00-8373-11eb-9e4e-9b0c8e0d9162.png)

and then i delete number 3 data
the result is like this
![image](https://user-images.githubusercontent.com/37582643/110948442-ee742980-8373-11eb-9d40-7ea25538b797.png)

### Bug Number 4
when my data like this
![image](https://user-images.githubusercontent.com/37582643/110948609-24191280-8374-11eb-9866-5fab6b088d7a.png)

and then i delete data number 3 and number 4
the result is like this
![image](https://user-images.githubusercontent.com/37582643/110948692-3eeb8700-8374-11eb-9089-4b428e9461da.png)

**Comment by geofany** [comment]
@WisnuDS Reset Button just work on Number 1 data. not work on another data
![image](https://user-images.githubusercontent.com/37582643/111118926-062df680-859c-11eb-9b43-755fd4e0fa07.png)

**Comment by WisnuDS** [comment]
done
