### ISSUE TITLE
Invalid Local History Word Counter

### ISSUE THREAD

**Issue by geofany** [cmlabsdev/tools#402]
when there is no local storage it's not showing anything
![image](https://user-images.githubusercontent.com/37582643/111100574-a07d4280-857a-11eb-9fa1-59752086b45b.png)

it must be like this
![image](https://user-images.githubusercontent.com/37582643/111100605-b1c64f00-857a-11eb-862a-4f6c73123e88.png)

**Comment by WisnuDS** [comment]
done
