### ISSUE TITLE
Bug on Local Storage Logic

### ISSUE THREAD

**Issue by geofany** [cmlabsdev/tools#403]
when i have local storage data like this
![image](https://user-images.githubusercontent.com/37582643/111100767-0f5a9b80-857b-11eb-85a5-9e6ea1c058fb.png)

and then i delete i 1 by 1 per item (not using clear all)
then reach 0 data, this text is not showing
![image](https://user-images.githubusercontent.com/37582643/111100852-429d2a80-857b-11eb-8565-4b992e8f6c51.png)

![image](https://user-images.githubusercontent.com/37582643/111100811-28634c80-857b-11eb-81c9-1403e7534e5c.png)

this is because there is Empty Array on local storage
![image](https://user-images.githubusercontent.com/37582643/111100894-5ba5db80-857b-11eb-817d-999dcc32bf0b.png)

but if i click Clear All
it showing again, because the Empty Array is gone
![image](https://user-images.githubusercontent.com/37582643/111100947-76785000-857b-11eb-8644-82a28ba09af3.png)

Tools that use this Logic :
- [x] Word Counter
- [x] Meta Checker
- [x] Page Speed Test
- [x] Sitemap Generator
- [x] SSL Checker

**Comment by WisnuDS** [comment]
done
